### ISSUE TITLE
Error speed work

### ISSUE THREAD

**Issue by john07-max** [fenicks/minaxnt#5]
since update 0.13.2 when I run the mine with the command:

minaxnt.exe --node http://mainnet.axentro.io --address TTBjMjg1NWJmZTIwMTA3MDc3NTZkNjg1MTcxYjE1YmE5ZjU3N2EzODhkYWRiZWIy --process 2

The working speed remains at 0 then the mine closes after a few minutes. while with version 0.12 everything works normally with a working speed of 29Work/s.

INFO[2021-05-29T22:39:09+02:00] Total Speed: 0.0 Work/s, Time: 10.0s
INFO[2021-05-29T22:39:19+02:00] Total Speed: 0.0 Work/s, Time: 10.1s

**Comment by christiankakesa** [comment]
Hi,
Can you retry, the mainnet version of the blockchain deployment took more time than we expected.
Looks OK now.

**Comment by john07-max** [comment]
Ok, I have tried and everything is working fine!
